version: '3'

services:
  web:
    build: .
    ports:
      - 5000:80
    links:
      - mysql
    env_file:
      - .env
    environment:
      WEB_HOST: http://localhost:8080
  
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gabber
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
