version: '3'

services:
  web:
    build: .
    ports:
      - 5000:80
    links:
      - mysql
    volumes:
      - ./gabber:/app/gabber
    env_file:
      - .env
    environment:
      SECRET_KEY: super-duper-secret
      SALT: really-not-secret
      JWT_SECRET: now-this-one-is-secret
      WEB_HOST: http://localhost:8080
      DATABASE_URL: mysql+pymysql://user:secret@mysql/gabber?charset=utf8mb4
      APP_MODE: dev

  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gabber
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
